In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter('ignore')

In [2]:
train_data = pd.read_csv('SalaryData_Train(1).csv')

In [3]:
train_data

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

In [4]:
train_data.describe()

age   educationno   capitalgain   capitalloss  hoursperweek
count  30161.000000  30161.000000  30161.000000  30161.000000  30161.000000
mean      38.438115     10.121316   1092.044064     88.302311     40.931269
std       13.134830      2.550037   7406.466611    404.121321     11.980182
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       47.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   4356.000000     99.000000

In [5]:
train_data['native'].unique()

array([' United-States', ' Cuba', ' Jamaica', ' India', ' Mexico',
       ' Puerto-Rico', ' Honduras', ' England', ' Canada', ' Germany',
       ' Iran', ' Philippines', ' Poland', ' Columbia', ' Cambodia',
       ' Thailand', ' Ecuador', ' Laos', ' Taiwan', ' Haiti', ' Portugal',
       ' Dominican-Republic', ' El-Salvador', ' France', ' Guatemala',
       ' Italy', ' China', ' South', ' Japan', ' Yugoslavia', ' Peru',
       ' Outlying-US(Guam-USVI-etc)', ' Scotland', ' Trinadad&Tobago',
       ' Greece', ' Nicaragua', ' Vietnam', ' Hong', ' Ireland',
       ' Hungary'], dtype=object)

In [6]:
train_data['Salary'].value_counts()

 <=50K    22653
 >50K      7508
Name: Salary, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le=LabelEncoder()
train_data['workclass']=le.fit_transform(train_data['workclass'])
train_data['education']=le.fit_transform(train_data['education'])
train_data['maritalstatus']=le.fit_transform(train_data['maritalstatus'])
train_data['occupation']=le.fit_transform(train_data['occupation'])
train_data['relationship']=le.fit_transform(train_data['relationship'])
train_data['race']=le.fit_transform(train_data['race'])
train_data['sex']=le.fit_transform(train_data['sex'])
train_data['native']=le.fit_transform(train_data['native'])
train_data['Salary']=le.fit_transform(train_data['Salary'])

In [9]:
train_data

age  workclass  education  educationno  maritalstatus  occupation  \
0       39          5          9           13              4           0   
1       50          4          9           13              2           3   
2       38          2         11            9              0           5   
3       53          2          1            7              2           5   
4       28          2          9           13              2           9   
...    ...        ...        ...          ...            ...         ...   
30156   27          2          7           12              2          12   
30157   40          2         11            9              2           6   
30158   58          2         11            9              6           0   
30159   22          2         11            9              4           0   
30160   52          3         11            9              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 1     4    1         2174            0            40   
1                 0     4    1            0            0            13   
2                 1     4    1            0            0            40   
3                 0     2    1            0            0            40   
4                 5     2    0            0            0            40   
...             ...   ...  ...          ...          ...           ...   
30156             5     4    0            0            0            38   
30157             0     4    1            0            0            40   
30158             4     4    0            0            0            40   
30159             3     4    1            0            0            20   
30160             5     4    0        15024            0            40   

       native  Salary  
0          37       0  
1          37       0  
2          37       0  
3          37       0  
4           4       0  
...       ...     ...  
30156      37       0  
30157      37       1  
30158      37       0  
30159      37       0  
30160      37       1  

[30161 rows x 14 columns]

In [10]:
# feature selection: tree based feature selection
from sklearn.tree import DecisionTreeClassifier
x_train = train_data.iloc[:,0:13]
y_train = train_data.iloc[:,13]
x_train.shape,y_train.shape

((30161, 13), (30161,))

In [11]:
x_train

age  workclass  education  educationno  maritalstatus  occupation  \
0       39          5          9           13              4           0   
1       50          4          9           13              2           3   
2       38          2         11            9              0           5   
3       53          2          1            7              2           5   
4       28          2          9           13              2           9   
...    ...        ...        ...          ...            ...         ...   
30156   27          2          7           12              2          12   
30157   40          2         11            9              2           6   
30158   58          2         11            9              6           0   
30159   22          2         11            9              4           0   
30160   52          3         11            9              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  
0                 1     4    1         2174            0            40      37  
1                 0     4    1            0            0            13      37  
2                 1     4    1            0            0            40      37  
3                 0     2    1            0            0            40      37  
4                 5     2    0            0            0            40       4  
...             ...   ...  ...          ...          ...           ...     ...  
30156             5     4    0            0            0            38      37  
30157             0     4    1            0            0            40      37  
30158             4     4    0            0            0            40      37  
30159             3     4    1            0            0            20      37  
30160             5     4    0        15024            0            40      37  

[30161 rows x 13 columns]

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)

In [13]:
x_train

array([[ 0.04277892,  2.93594688, -0.34982703, ..., -0.21850808,
        -0.07773541,  0.26635842],
       [ 0.88026081,  1.88764517, -0.34982703, ..., -0.21850808,
        -2.33149486,  0.26635842],
       [-0.0333558 , -0.20895825,  0.1748048 , ..., -0.21850808,
        -0.07773541,  0.26635842],
       ...,
       [ 1.48933854, -0.20895825,  0.1748048 , ..., -0.21850808,
        -0.07773541,  0.26635842],
       [-1.25151126, -0.20895825,  0.1748048 , ..., -0.21850808,
        -1.74718685,  0.26635842],
       [ 1.03253024,  0.83934346,  0.1748048 , ..., -0.21850808,
        -0.07773541,  0.26635842]])

In [14]:
from sklearn.tree import DecisionTreeClassifier
dt_model= DecisionTreeClassifier(criterion ="entropy" , random_state = 0)
dt_model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [15]:
from sklearn.metrics import confusion_matrix , accuracy_score

In [16]:
y_prad = dt_model.predict(x_train)

In [17]:
accuracy_score(y_prad , y_train)

0.9750339842843407

In [18]:
cm = confusion_matrix(y_prad , y_train)
cm 

array([[22528,   628],
       [  125,  6880]], dtype=int64)

In [19]:
#svm using whole features:
from sklearn.svm import SVC
svm= SVC(kernel='rbf',random_state=0,gamma=0.1,C=1.0)
svm.fit(x_train,y_train)

SVC(gamma=0.1, random_state=0)

In [20]:
y_prad_1  = svm.predict(x_train)

In [21]:
accuracy_score(y_prad_1 , y_train)

0.8542488644275721

# only useful feature and train model

In [22]:
dt_model.feature_importances_

array([0.19137146, 0.0511792 , 0.02192265, 0.11217659, 0.0151396 ,
       0.08610599, 0.2137824 , 0.02112561, 0.00497354, 0.11883088,
       0.03989721, 0.10505893, 0.01843594])

In [23]:
l= dt_model.feature_importances_>0.1
l

array([ True, False, False,  True, False, False,  True, False, False,
        True, False,  True, False])

In [24]:
new_x_train = train_data.iloc[:,[0,3,6,9,11]]
new_x_train.head()

age  educationno  relationship  capitalgain  hoursperweek
0   39           13             1         2174            40
1   50           13             0            0            13
2   38            9             1            0            40
3   53            7             0            0            40
4   28           13             5            0            40

In [25]:
new_x_train = sc.fit_transform(new_x_train)

In [26]:
new_x_train

array([[ 0.04277892,  1.12889813, -0.26123312,  0.14608503, -0.07773541],
       [ 0.88026081,  1.12889813, -0.88571218, -0.14744712, -2.33149486],
       [-0.0333558 , -0.4397325 , -0.26123312, -0.14744712, -0.07773541],
       ...,
       [ 1.48933854, -0.4397325 ,  1.61220404, -0.14744712, -0.07773541],
       [-1.25151126, -0.4397325 ,  0.98772499, -0.14744712, -1.74718685],
       [ 1.03253024, -0.4397325 ,  2.2366831 ,  1.88108414, -0.07773541]])

In [27]:
from sklearn.svm import SVC
svm_1 = SVC(kernel='rbf',random_state=0,gamma=0.10, C=1.0)
svm_1 .fit(new_x_train,y_train)

SVC(gamma=0.1, random_state=0)

In [28]:
y_prad_2  = svm_1.predict(new_x_train)

In [29]:
accuracy_score(y_prad_2 , y_train)

0.8417824342694208

In [30]:
cm_1 = confusion_matrix(y_prad_2 , y_train)

In [31]:
cm_1

array([[21452,  3571],
       [ 1201,  3937]], dtype=int64)